# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80e9ba8ea1556297d6f5be46dbd589d919c958baab5d88f67252d9ee48ce071b0d261ae611ae42e3732c1f9da824d0738fa4230f4ac2440768290829cb723aef
  plaid_client_id: 55e87d503b5cadf40371c505
  plaid_secret: 95b97620691513ae42c6efa26f36e7
  stripe_api_key: sk_test_r3eM9inZiCYjc8VYopmAhRPY
test:
  secret_key_base: 1ed99b25d98899f6ca94664d7aa6ef68190dd15bf994c717b3081d7a5df13f03992675d6ccf4bb1cb532b94d95b2e28f04e61e9caa4a363875678d731b415817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  plaid_client_id: <%= ENV["PLAID_CLIENT_ID"] %>
  plaid_secret: <%= ENV["PLAID_SECRET"] %>
